project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: 1
files:
  - source: /blog/**/*.md
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-blog/%original_path%/%original_file_name%
  - source: /docs/**/*.md
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/%original_path%/%original_file_name%
